name: "Terraform"

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: "Select Terraform action"
        options:
          - apply
          - destroy
        required: true
  push:
    branches: ["main"]

jobs:
  terraform:
    name: "Terraform"
    env:
      # AWS SECRETS
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CLI_SECRET_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CLI_SECRET_KEY_PASS }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init -input=false

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var="instance_type=t2.micro"

      # Conditional Apply
      - name: Terraform Apply
        if: ${{ github.event.inputs.terraform_action == 'apply' }}
        run: terraform apply -auto-approve -var="instance_type=t2.micro"

      # Conditional Destroy
      - name: Terraform Destroy
        if: ${{ github.event.inputs.terraform_action == 'destroy' }}
        run: terraform destroy -auto-approve -var="instance_type=t2.micro"
